### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by cscherrer** [slimgroup/InvertibleNetworks.jl#32]
Hi, 
Thanks for your work on this package, I enjoyed your JuliaCon talk! Do you have an estimate when this might be available on the general registry?

**Comment by mloubout** [comment]
Hi

As of now, due to the packages we work on and develop, we have our own registry (as shown in the README) which makes it more manageable due to some packages being private for development.
We don't have a current timeline on switching to the general registry but we will discuss it and may change that.


I'll leave this open for others to comment and discuss and updates on the status.

**Comment by cscherrer** [comment]
Thanks for the quick response. I understand there are tradeoffs to consider. A registered package is a little easier to use, but it's great to have this available at all, especially with an MIT license. :)

**Comment by mloubout** [comment]
We will be working on releasing it. Since it depends on other packages from our registry it will take a little bit as we will need to register these dependencies first.

**Comment by mloubout** [comment]
We are now released and available in the general registry. 

Closing.
